### ISSUE TITLE
Add unit and integration tests, continous deployment

### ISSUE THREAD

**Issue by nfriedly** [Differential/supporter#52] opened 2013-12-13 15:11 UTC
@ryw and I made some good progress on unit tests, and I just got some integration tests to work nicely with my ODB-II site with [CasperJS](http://casperjs.org/):

config: https://github.com/nfriedly/Meteor-ODB-II/blob/master/.travis.yml

setup: https://github.com/nfriedly/Meteor-ODB-II/blob/master/tests/pre_test.sh

test: https://github.com/nfriedly/Meteor-ODB-II/blob/master/tests/integration.casper.js

results: https://travis-ci.org/nfriedly/Meteor-ODB-II/builds/15402566

I've learned a few things along the way:
- Meteor tries to parse anything in the `node_modules/` folder, which means you pretty much can't use it. Fortunately just about every testing library can be installed globally, hence my `pre_test.sh` script.
- Meteor has a special exception for folders named `tests/` (plural) - it ignores everything in that folder. As far as I can tell, this is the only such exception that exists.

I do still want to look into https://github.com/WebReflection/wru but I just thought I'd share the progress I made here :)

**Comment by queso** [comment] 2013-12-13 15:48
It is also supposed to ignore any folders ending in ~, but I believe that is highly undocumented.  This is great stuff @nfriedly!

**Comment by ryw** [comment] 2014-05-19 02:12
this is a dupe of #53 — @nfriedly would love you to look at velocity and get your feedback on it. you might be interested in joining the group that is working on that project (@queso and myself have been on the calls).

**Closed as completed by ryw** 2014-05-19 02:12 UTC
